APPMVC/Areas/Admin/Controllers/ChatLieuController.cs
using AppData.Model;
using APPMVC.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using X.PagedList;

namespace APPMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ChatLieuController : Controller
    {
        public IChatLieuService _services;

        public ChatLieuController(IChatLieuService services)
        {
            _services = services;
        }

        [HttpGet]
        public async Task<IActionResult> Getall(string? name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 5;
            List<ChatLieu> timten = await _services.GetChatLieu(name);
            if (timten != null)
            {
                var pagedChatLieux = timten.ToPagedList(page, pageSize);
                return View(pagedChatLieux);
            }
            else
            {
                List<ChatLieu> chatLieux = await _services.GetChatLieu(name);
                var pagedChatLieux = chatLieux.ToPagedList(page, pageSize);
                return View(pagedChatLieux);
            }
        }

        public IActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(ChatLieu chatLieu)
        {
            if (!ModelState.IsValid)
            {
                if (ModelState.ContainsKey("TenChatLieu"))
                {
                    var error = ModelState["TenChatLieu"].Errors.FirstOrDefault();
                    if (error != null)
                    {
                        TempData["Error"] = error.ErrorMessage;
                    }
                }
                return RedirectToAction("Getall");
            }
            try
            {
                await _services.Create(chatLieu);
                TempData["Success"] = "Thêm mới thành công";
            }
            catch (Exception)
            {
                TempData["Error"] = "Thêm mới thất bại";
            }
            return RedirectToAction("Getall");
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var chatLieu = await _services.GetChatLieuById(id);
            if (chatLieu == null)
            {
                return NotFound();
            }
            return View(chatLieu);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(ChatLieu chatLieu)
        {
            if (!ModelState.IsValid)
            {
                // Kiểm tra tính hợp lệ của dữ liệu
                if (ModelState.ContainsKey("TenChatLieu"))
                {
                    var error = ModelState["TenChatLieu"].Errors.FirstOrDefault();
                    if (error != null)
                    {
                        TempData["Error"] = error.ErrorMessage;
                    }
                }
                return View(chatLieu);
            }
            try
            {
                await _services.Update(chatLieu);
                TempData["Success"] = "Cập nhật thành công";
            }
            catch (Exception)
            {
                TempData["Error"] = "Cập nhật thất bại";
            }
            return RedirectToAction("Getall");
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            try
            {
                await _services.Delete(id);
                TempData["Success"] = "Xóa thành công";
            }
            catch (Exception)
            {
                TempData["Error"] = "Xóa thất bại";
            }
            return RedirectToAction("Getall");
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var chatLieu = await _services.GetChatLieuById(id);
            if (chatLieu == null)
            {
                return NotFound();
            }
            return View(chatLieu);
        }
    }
}

APPMVC/Areas/Admin/Views/ChatLieu/Create.cshtml
@model AppData.Model.ChatLieu
@{
    ViewData["Title"] = "Create";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Tạo mới chất liệu</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="TenChatLieu" class="control-label" style="margin-bottom:2px">Tên Chất Liệu</label>
                    <input asp-for="TenChatLieu" class="form-control" />
                    <span asp-validation-for="TenChatLieu" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="NgayCapNhat" class="control-label"></label>
                    <input asp-for="NgayCapNhat" class="form-control" type="date" asp-format="{0:yyyy-MM-dd}" />
                    <span asp-validation-for="NgayCapNhat" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="NgayTao" class="control-label"></label>
                    <input asp-for="NgayTao" class="form-control" type="date" asp-format="{0:yyyy-MM-dd}" />
                    <span asp-validation-for="NgayTao" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="NguoiCapNhat" class="control-label"></label>
                    <input asp-for="NguoiCapNhat" class="form-control" />
                    <span asp-validation-for="NguoiCapNhat" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="NguoiTao" class="control-label"></label>
                    <input asp-for="NguoiTao" class="form-control" />
                    <span asp-validation-for="NguoiTao" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="KichHoat" class="control-label"></label>
                    <input asp-for="KichHoat" class="form-control" />
                    <span asp-validation-for="KichHoat" class="text-danger"></span>
                </div>
                <div class="form-group" style="margin-top: 10px; text-align:center">
                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

APPMVC/Areas/Admin/Views/ChatLieu/Edit.cshtml
@model AppData.Model.ChatLieu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Quản lý sản phẩm /</span> Chất Liệu Chi Tiết
        </h4>
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4" style="padding: 20px;">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdChatLieu" />

                        <div class="nav-item d-flex align-items-center flex-column">
                            <div class="form-group mb-3">
                                <label asp-for="TenChatLieu" class="control-label">Tên Chất Liệu</label>
                                <input asp-for="TenChatLieu" class="form-control" />
                                <span asp-validation-for="TenChatLieu" class="text-danger"></span>
                            </div>
                            <div class="form-group" hidden>
                                <label asp-for="NgayCapNhat" class="control-label">Ngày Cập Nhât</label>
                                <input asp-for="NgayCapNhat" class="form-control" type="date" asp-format="{0:yyyy-MM-dd}" />
                                <span asp-validation-for="NgayCapNhat" class="text-danger"></span>
                            </div>
                            <div class="form-group" hidden>
                                <label asp-for="NgayTao" class="control-label">Ngày tạo</label>
                                <input asp-for="NgayTao" class="form-control" type="date" asp-format="{0:yyyy-MM-dd}" />
                                <span asp-validation-for="NgayTao" class="text-danger"></span>
                            </div>
                            <div class="form-group" hidden>
                                <label asp-for="NguoiCapNhat" class="control-label">Người Cập Nhật</label>
                                <input asp-for="NguoiCapNhat" class="form-control" />
                                <span asp-validation-for="NguoiCapNhat" class="text-danger"></span>
                            </div>
                            <div class="form-group" hidden>
                                <label asp-for="NguoiTao" class="control-label">Người Tạo</label>
                                <input asp-for="NguoiTao" class="form-control" />
                                <span asp-validation-for="NguoiTao" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="KichHoat" class="control-label">Kích Hoạt</label>
                                <div>
                                    <input type="radio" asp-for="KichHoat" value="1" /> Hoạt động
                                    <input type="radio" asp-for="KichHoat" value="0" /> Không hoạt động
                                </div>
                                <span asp-validation-for="KichHoat" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group mb-3 d-flex justify-content-between">
                                <input type="submit" value="Save" class="btn btn-primary" />
                                <a asp-area="Admin" asp-action="Getall" class="btn btn-secondary" style="margin-left:15px;">Back to List</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

APPMVC/Areas/Admin/Views/ChatLieu/Getall.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<AppData.Model.ChatLieu>

@{
    ViewData["Title"] = "Get all";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success" style="padding: 10px; margin-right:20px;margin-top:20px; align-self:end; position: absolute">
            @TempData["Success"]
        </div>
    }
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger" style="padding: 10px; align-self:end;margin-right:20px;margin-top:20px; position: absolute">
            @TempData["Error"]
        </div>
    }
    <!-- Content -->
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Quản lý sản phẩm /</span> Chất Liệu
        </h4>
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success" style="padding: 10px; align-self:end; position: absolute">
                @TempData["Success"]
            </div>
        }
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger" style="padding: 10px; align-self:end; position: absolute">
                @TempData["Error"]
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4" style="padding: 20px">
                    <div class="nav-item d-flex align-items-center" style="display: flex; justify-content: space-between;">
                        <form action="Getall" method="get" style="display: flex; align-items: center;">
                            <i class="bx bx-search fs-4 lh-0"></i>
                            <input type="text" name="name" class="form-control border-1 shadow-none" placeholder="Search by name..." aria-label="Search..." />
                            <button type="submit" title="Search" style="margin-left: 10px; padding: 5px 10px; border: none; border-radius: 5px; background-color: #4CAF50; color: #fff; cursor: pointer;">Tìm</button>
                        </form>
                        <a asp-action="Create" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal" style="margin-left: 10px;">Create New</a>

                    </div>
                    <br>
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Mã Chất Liệu</th>
                                    <th>Tên chất liệu</th>
                                    <th hidden>Ngày cập nhật</th>
                                    <th>Ngày tạo</th>
                                    <th hidden>Người cập nhật</th>
                                    <th hidden>Người tạo</th>
                                    <th>Kích hoạt</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr style="border-bottom: 1px solid #dee2e6;">
                                        <td>@item.IdChatLieu.ToString().Substring(0, 5)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TenChatLieu)</td>
                                        <td hidden>@Html.DisplayFor(modelItem => item.NgayCapNhat)</td>
                                        <td>@item.NgayTao.ToString("dd/MM/yyyy")</td>
                                        <td hidden>@Html.DisplayFor(modelItem => item.NguoiCapNhat)</td>
                                        <td hidden>@Html.DisplayFor(modelItem => item.NguoiTao)</td>
                                        <td>
                                            @(item.KichHoat == 1 ? "Hoạt động" : "Không hoạt động")
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.IdChatLieu" title="Edit">
                                                <i class="fa-solid fa-pen"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="pagination">
                        @Html.PagedListPager(Model, Page => Url.Action("Getall", "ChatLieu", new { Page = Page }),
                                 new PagedListRenderOptions
                        {
                            DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                            DisplayLinkToLastPage = PagedListDisplayMode.Always,
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                            DisplayLinkToNextPage = PagedListDisplayMode.Always,
                            MaximumPageNumbersToDisplay = 5,
                            LiElementClasses = new string[] { "page-item" },
                            PageClasses = new string[] { "page-link" }
                        })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Add this code before the closing `</div>` tag of your content wrapper -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-body">
            @Html.Partial("Create", new AppData.Model.ChatLieu
       {
           TenChatLieu = "Hieudz",
           NgayCapNhat = DateTime.Now,
           NgayTao = DateTime.Now,
           NguoiCapNhat = "admin",
           NguoiTao = "admin",
           KichHoat = 1,
       })

        </div>
    </div>
</div>